### ISSUE TITLE
Do not capitalize all words in headings for Russian language

### ISSUE THREAD

**Issue by Grawl** [HugoGiraudel/sass-guidelines#163]
I heard that in some languages the Germanic language group decided to write capitalized each word in the titles. In Russian we do not do that.
I think it's a good reason to add some CSS to different translations. Like `en/style.scss` for English and move `h1, h2, h3 { text-transform: capitalize }` there.

**Comment by HugoGiraudel** [comment]
I think we should keep it simple with:

```scss
:lang(ru) {
  h1, h2, h3 {
    text-transform: initial;
  }
}
```

Do you want to submit a PR?
