### ISSUE TITLE
@charset Double-quotes?

### ISSUE THREAD

**Issue by mikemclin** [HugoGiraudel/sass-guidelines#255]
My PhpStorm barked at me today when I entered my charset with single quotes.  It told me that double-quotes were required for the `@charset` declaration.

After doing a bit of research on the subject, I found this...

http://www.w3.org/TR/css3-syntax/#charset-rule

> Therefore, an @charset rule may appear in the object model even if it was ignored by that algorithm. (For instance, if it was written with extra whitespace or with single rather than double quotes.)

That makes me think that using single-quotes comes with the same repercussions as having white-space  before the declaration.  It'll be ignored when running the initial algorithm when determining the fallback encoding for the document.

I'm not going to pretend I am an expert on the matter...  Like I said, my IDE gave me a notice, so I did a bit of research.  I couldn't find any issues in this Github project when searching for `charset`, so I figured I'd bring it up for discussion.

**Comment by HugoGiraudel** [comment]
Very interesting issue. I will investigate. Thank you for your thoughts.

**Comment by HugoGiraudel** [comment]
Alright, so apparently Sass makes sure `@charset` is using double quotes when compiling, so no matter how you author it, it will be fine once in the browser. And this is a good behaviour as quotes should be a matter of stylistic preferences, not having an impact on the output. Although I feel like I should make this explicit in the docs.

**Comment by mikemclin** [comment]
Good to know.  Actually, **libsass** works completely differently, and apparently handles the `@charset` for you.  This is what I found when running my project through `grunt-sass`...

---

### Removes unnecessary `@charset` definition

#### Input

```scss
@charset "UTF-8";

p::before {
  color: aqua
}
```

#### Output

```css
p::before {
  color: aqua;
}
```

---

### Adds `@charset` when needed

#### Input

```scss
p::before {
  color: aqua;
  content: "Hëllö world!"; 
}
```

#### Output

```css
@charset "UTF-8";

p::before {
  color: aqua;
  content: "Hëllö world!"; 
}
```

---

### Ignores user declared `@charset` (always uses `UTF-8`)

#### Input

```scss
@charset "UTF-16";

p::before {
  color: aqua;
  content: "Hëllö world!"; 
}
```

#### Output

```scss
@charset "UTF-8";

p::before {
  color: aqua;
  content: "Hëllö world!"; 
}
```
