### ISSUE TITLE
Accessibility: "Skip Link" needed

### ISSUE THREAD

**Issue by innovandrew** [HugoGiraudel/sass-guidelines#309]
This is one of the most important accessibility features. This resolves major concerns for keyboard and screen reader users.

This is very simple to implement.

Markup
---------
Must be placed immediately following `<body>` tag.

```html
<a id="skip" href="#main">Skip to main content</a>
```

CSS (SCSS)
-------
```scss
#skip {
	display: block;
	background: #fff;
	color: rgba(0,0,0,0.87);
	line-height: 1.625rem;
	padding: .875rem 1.625rem;
	text-decoration: none;
	border: 1px solid rgba(0,0,0,0.25);
	position: absolute;
	right: 1.625rem;
	top: -2.625rem;
	font-size: 1.333em;
	overflow: hidden;
	height: 1px;
	width: 1px;
}
```

Don't forget to place an "ID" on your `<main>` tag. Like: 
```html
<main id="main" role="main">

<!-- or, for folks with divitis: -->
<div id="main" role="main" class="content-wrapper-row-column-grid-what-are-semantics">
```

[Demo](http://codepen.io/innovandrew/pen/xZPRWP)
[More info](http://webaim.org/techniques/skipnav/)
