### ISSUE TITLE
Rulesets and media-queries

### ISSUE THREAD

**Issue by indrekpaas** [HugoGiraudel/sass-guidelines#44]
Media-queries in rulesets should immediately follow element's declarations. Otherwise if a ruleset is to contain other (sometimes many) nested elements, the media-query related to the element is shifting context and is less readable.

```scss
.foo {
  display: none;

  @include respond-to("small") {
    display: block;
  }

  .bar { ... }

  span { ... }

  &:hover {
    color: red;

    .bar { ... }
  }
}
```

A very good guide of [Outlining a system for writing Sass](https://gist.github.com/jesgundy/5879190).
