### ISSUE TITLE
Grouping of CSS properties within a selector block

### ISSUE THREAD

**Issue by jigarjain** [HugoGiraudel/sass-guidelines#64]
How about also following a pattern of grouping/ordering of CSS properties? It makes the code more readable & easy to find where a particular property will be available or should be placed.

Ex: What many people do
```css
.goodlooking-box {
    font-size: 14px;
    display: inline;
    margin: 10px;
    color: #EFEFEF;
    border: 1px solid #EEE;
    font-weight: bold;
    text-transform: uppercase;
    cursor: pointer;
    padding: 15px 10px;
    margin-top: 15px;
}
```
Here is what I am suggesting
```css
.goodlooking-box {
    display: inline;
    margin: 10px;
    margin-top: 15px;
    padding: 15px 10px;
    /**  width, height, position, top, left, right, bottom etc **/
    font-size: 14px;
    font-weight: bold;
    /** font-family, font-style, line-height etc **/
    color: #EFEFEF;
    text-transform: uppercase;
    border: 1px solid #EEE;
    /** background, outline, border-radius, box-shadow etc **/
    cursor: pointer;
    /** z-index, content etc **/
}
```
Yes, there is no strict rule or pattern here. But I believe this is still better than the first example where there is a good chance of a property getting repeated again.
Let me know what yo guys think :)
