### ISSUE TITLE
CSS Named Colors 

### ISSUE THREAD

**Issue by una** [HugoGiraudel/sass-guidelines#75]
I'm just wondering why you recommend using named colors. I always avoid them as a general rule because of the potential that they may be output as their hex value in compressed mode when referenced in maps (i.e. why you always quote named colors in maps).

I know you know this, but here's a visual reference:
https://gist.github.com/una/83cd6d4feb16b3ebcb01

So it seems like it would be a best practice to avoid them altogether for consistency.

**Comment by HugoGiraudel** [comment]
Hey Una.

Color keywords are there for a reason, and a good one: there are far simpler to deal with than hexadecimal code. Some skilled designers might be able to mentally compute a color from an hexadecimal code, but most people certainly are not.

Now, regarding your example, this is typically the piece of Sass code that should not be written. `darkolivegreen`, `firebrick`, `blanchedalmond` are colors, not strings. Because of this, they should not be interpolated in a selector. 

Along the same lines, using color names as class names is probably a bad idea for maintainability, since you are now tied to a very specific color that cannot be changed without risking any further confusion. An appropriate way to write the aforementionned snippet would be:

```scss
$colors: (
  'darkolivegreen': #556b2f,
  'firebrick': #b22222,
  'blanchedalmond': #ffebcd
);

@each $key, $value in $colors {
  .item-#{$key} {
    color: $value;
  }
}
```

Hope it's now clear. :)
